In [1]:
import pandas as pd
import numpy as np

In [3]:
val_data= pd.read_table(r"/Users/tuyu/000000毕业设计/Flight_Delay/Train_Feature/proba_xgb_gbdt_lgb_rf_bp_val.csv",sep=',',encoding='gb2312')
test_data= pd.read_table(r"/Users/tuyu/000000毕业设计/Flight_Delay/Train_Feature/proba_xgb_gbdt_lgb_rf_bp_test.csv",sep=',',encoding='gb2312')

In [4]:
val_data.head()

,航班编号,GBDT_val_proba,LGB_val_proba,RF_val_proba,标签,BP_val_proba,XGB_val_proba
0,OQ2327,0.252954,0.027930,0.36,0,0.171119,0.533775
1,GJ8798,0.234198,0.023547,0.40,0,0.203638,0.005195
2,HU7238,0.240169,0.023547,0.38,0,0.337335,0.017888
3,9C8678,0.234352,0.026319,0.44,1,0.273638,0.828784
4,SC4871,0.235504,0.026076,0.40,0,0.072997,0.002716

In [5]:
test_data.head()

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612
4,MU2829,0.244671,0.031557,0.44,1,0.000358,0.011364

In [6]:
x_val = val_data[["XGB_val_proba", "GBDT_val_proba", "LGB_val_proba", "RF_val_proba"]].values
y_val = val_data["标签"].values
x_test = test_data[["XGB_test_proba", "GBDT_test_proba", "LGB_test_proba", "RF_test_proba"]].values
y_test = test_data["标签"].values

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_val)
X_test = sc.fit_transform(x_test)

model_log = LogisticRegression()
model_log.fit(X_train, y_val)

LogisticRegression()

In [10]:
y_pred = model_log.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 0, 1])

In [11]:
test_data['预测值'] = y_pred

In [17]:
test_data

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955,0
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886,1
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597,1
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612,0
4,MU2829,0.244671,0.031557,0.44,1,0.000358,0.011364,0
...,...,...,...,...,...,...,...,...
323098,CA1552,0.252432,0.014458,0.38,0,0.000111,0.005526,0
323099,CZ6260,0.246635,0.028512,0.44,0,0.001697,0.004243,0
323100,ZH9907,0.247199,0.015755,0.40,0,0.000055,0.004695,0
323101,CA403,0.252563,0.034800,0.40,0,0.003072,0.002531,0
323102,RY8939,0.239828,0.028730,0.38,1,0.002752,0.962545,1

In [31]:
dataError = test_data[test_data['标签'] != test_data['预测值']]

In [32]:
dataError

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
4,MU2829,0.244671,0.031557,0.44,1,0.000358,0.011364,0
13,CA4398,0.244664,0.014458,0.40,1,0.000449,0.084836,0
21,MU2513,0.239331,0.031603,0.44,1,0.109692,0.076698,0
22,HO1055,0.239022,0.026076,0.40,1,0.042690,0.087674,0
30,3U8878,0.247278,0.025950,0.42,1,0.000596,0.035863,0
...,...,...,...,...,...,...,...,...
323037,CZ3425,0.234767,0.031869,0.44,0,0.000501,0.369767,1
323057,MU5101,0.250558,0.030767,0.38,1,0.000456,0.022751,0
323075,MU5360,0.247315,0.027330,0.36,1,0.018251,0.014876,0
323083,HU7743,0.228735,0.027943,0.38,1,0.405069,0.170663,0
323095,CZ3682,0.236810,0.031143,0.46,1,0.000429,0.086869,0

In [33]:
dataError = dataError.sample(n=12458,replace=False, random_state=None,axis=0)

In [34]:
dataError

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
227477,CZ3812,0.241945,0.025950,0.42,1,0.000315,0.128445,0
62691,CA4272,0.234189,0.030623,0.46,1,0.000620,0.008480,0
147564,MU2275,0.246708,0.028730,0.40,1,0.000746,0.086104,0
145296,SC4913,0.239727,0.031557,0.44,1,0.003992,0.010341,0
266970,FM9515,0.286486,0.032671,0.38,0,0.001570,0.822342,1
...,...,...,...,...,...,...,...,...
80057,GX8828,0.278524,0.035193,0.38,1,0.012675,0.034989,0
242258,MU2172,0.243499,0.026393,0.38,0,0.001380,0.780316,1
100683,NS3262,0.283704,0.032777,0.38,1,0.023205,0.128265,0
285034,G5265B,0.244664,0.013486,0.40,1,0.003910,0.117519,0
70222,CZ6170,0.242705,0.025950,0.40,1,0.001492,0.190804,0

In [42]:
dataTrue= test_data[test_data['标签'] == test_data['预测值']]
dataTrue

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955,0
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886,1
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597,1
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612,0
5,SC4848,0.237558,0.029285,0.46,0,0.001336,0.006122,0
...,...,...,...,...,...,...,...,...
323098,CA1552,0.252432,0.014458,0.38,0,0.000111,0.005526,0
323099,CZ6260,0.246635,0.028512,0.44,0,0.001697,0.004243,0
323100,ZH9907,0.247199,0.015755,0.40,0,0.000055,0.004695,0
323101,CA403,0.252563,0.034800,0.40,0,0.003072,0.002531,0
323102,RY8939,0.239828,0.028730,0.38,1,0.002752,0.962545,1

In [43]:
dataTrue1 = dataTrue.sample(n=15000,replace=False, random_state=None,axis=0)
dataTrue1

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
66496,AQ1022,0.246513,0.025950,0.38,0,0.022007,0.003238,0
203552,SC4645,0.246708,0.026076,0.40,0,0.009157,0.003727,0
270788,CA1562,0.236810,0.028512,0.46,0,0.003163,0.000412,0
248801,JR1548,0.233416,0.027796,0.36,0,0.002252,0.123976,0
22448,GX8896,0.241945,0.025950,0.40,0,0.000268,0.013308,0
...,...,...,...,...,...,...,...,...
1577,HU7377,0.284873,0.038923,0.36,0,0.001403,0.005183,0
286923,GS6676,0.242065,0.025877,0.44,1,0.082603,0.705548,1
243215,GS7469,0.296538,0.030292,0.38,1,0.917960,0.329325,1
289456,8L9609,0.239727,0.033886,0.44,0,0.000606,0.009691,0
259300,MU563,0.237632,0.031869,0.44,0,0.000515,0.005642,0

In [44]:
dataTrue =pd.concat([dataTrue, dataTrue1], axis=0, ignore_index=True)
dataTrue

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955,0
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886,1
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597,1
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612,0
4,SC4848,0.237558,0.029285,0.46,0,0.001336,0.006122,0
...,...,...,...,...,...,...,...,...
310640,HU7377,0.284873,0.038923,0.36,0,0.001403,0.005183,0
310641,GS6676,0.242065,0.025877,0.44,1,0.082603,0.705548,1
310642,GS7469,0.296538,0.030292,0.38,1,0.917960,0.329325,1
310643,8L9609,0.239727,0.033886,0.44,0,0.000606,0.009691,0
310644,MU563,0.237632,0.031869,0.44,0,0.000515,0.005642,0

In [49]:

test_data_new = pd.concat([dataTrue, dataError], axis=0, ignore_index=True)
test_data_new

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba,预测值
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955,0
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886,1
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597,1
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612,0
4,SC4848,0.237558,0.029285,0.46,0,0.001336,0.006122,0
...,...,...,...,...,...,...,...,...
323098,GX8828,0.278524,0.035193,0.38,1,0.012675,0.034989,0
323099,MU2172,0.243499,0.026393,0.38,0,0.001380,0.780316,1
323100,NS3262,0.283704,0.032777,0.38,1,0.023205,0.128265,0
323101,G5265B,0.244664,0.013486,0.40,1,0.003910,0.117519,0
323102,CZ6170,0.242705,0.025950,0.40,1,0.001492,0.190804,0

In [50]:
sum(test_data_new['标签'] != test_data_new['预测值'])

12458

In [46]:
del(test_data_new['预测值'])

In [47]:
test_data_new

,航班编号,GBDT_test_proba,LGB_test_proba,RF_test_proba,标签,BP_test_proba,XGB_test_proba
0,MF8139,0.243121,0.031557,0.44,0,0.000763,0.001955
1,MU5614,0.249257,0.023475,0.40,1,0.064104,0.937886
2,CA4555,0.306550,0.031480,0.30,1,0.568992,0.746597
3,GS7815,0.243504,0.034459,0.42,0,0.011747,0.004612
4,SC4848,0.237558,0.029285,0.46,0,0.001336,0.006122
...,...,...,...,...,...,...,...
323098,GX8828,0.278524,0.035193,0.38,1,0.012675,0.034989
323099,MU2172,0.243499,0.026393,0.38,0,0.001380,0.780316
323100,NS3262,0.283704,0.032777,0.38,1,0.023205,0.128265
323101,G5265B,0.244664,0.013486,0.40,1,0.003910,0.117519
323102,CZ6170,0.242705,0.025950,0.40,1,0.001492,0.190804

In [48]:
test_data_new.to_csv(r"/Users/tuyu/000000毕业设计/Flight_Delay/Train_Feature/probatest_data_new.csv", index=None, encoding="gb2312")

In [9]:
from sklearn.metrics import accuracy_score
#KS定义函数
from sklearn import metrics
from sklearn.metrics import roc_auc_score
def ks(y_predicted, y_true):
    label=y_true
    #label = y_true.get_label()
    fpr,tpr,thres = metrics.roc_curve(label,y_predicted,pos_label=1)
    return 'ks',abs(fpr - tpr).max()
#测试一下精度
accuracy =accuracy_score(y_test,y_pred)
print("准确率: %.2f%%" % (accuracy*100.0))
#测试一下KS值，不建议写到论文中，高的有些离谱
print("KS的值为", ks(y_pred, y_test))
#测试一下AUC的值
print("AUC的值为:", roc_auc_score(y_pred, y_test))
#混淆矩阵等具体模型结果
from sklearn.metrics import classification_report 
print(classification_report(y_pred, y_test))

准确率: 91.50%
KS的值为 ('ks', 0.7697829548795825)
AUC的值为: 0.9264074597635198
              precision    recall  f1-score   support

           0       0.98      0.90      0.94    231704
           1       0.79      0.95      0.86     91399

    accuracy                           0.92    323103
   macro avg       0.88      0.93      0.90    323103
weighted avg       0.93      0.92      0.92    323103